# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://flora.db.elephantsql.com/qahhmijs
    username: qahhmijs
    password: br5luxb8r-Lbq8ZgKzi45g_ziNSOecSY
  # JPA properties
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # Server configuration
  server:
    port: 8080
  # Security configuration
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv23liW1mGsrB8yfO7iC
            clientSecret: 9044122c4af66c70f73a0358d8a1a2dff86ac157

# Log4j configuration
logging:
  level:
    root: INFO
  file:
    name: logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  loggers:
    file:
      name: FILE
  appenders:
    file:
      type: File
      name: FILE
      fileName: "logs/application.log"
      pattern: "${logging.pattern.file}"
    console:
      type: Console
      name: STDOUT
      layout:
        pattern: "${logging.pattern.console}"
